name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci-lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.6

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v2
        with:
          reviewdog_version: latest

      - name: Run golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: 1.21.6
          golangci_lint_flags: './test/...'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: golangci
          level: error
          reporter: github-pr-check
          filter_mode: added
          fail_on_error: false
          workdir: .
